Repository DIT113-V22/group-04, pull requests merged in 2022-05, with the labels that each got.

#39 Implement MQTT subscription and event handling
  android/Drawer/app/build.gradle
  android/Drawer/app/src/main/AndroidManifest.xml
  android/Drawer/app/src/main/java/com/example/drawer/DrawControl.java
  android/Drawer/app/src/main/java/com/example/drawer/MQTTController.java
  android/Drawer/app/src/main/java/com/example/drawer/MainActivity.java
  android/Drawer/app/src/main/java/com/example/drawer/ManualControl.java
  android/Drawer/app/src/main/res/layout/activity_draw_control.xml
  android/Drawer/app/src/main/res/layout/activity_main.xml
  android/Drawer/app/src/main/res/layout/activity_manual_control.xml
Labels: enhancement, Sprint #2

#44 Implement camera capabilities
  android/Drawer/app/src/main/java/com/example/drawer/MQTTController.java
  android/Drawer/app/src/main/java/com/example/drawer/MainActivity.java
  android/Drawer/app/src/main/java/com/example/drawer/ManualControl.java
  arduino/smartcar/smartcar.ino
Labels: enhancement, Sprint #2

#47 Implements grid-based canvas
  android/Drawer/app/src/main/java/com/example/drawer/CanvasGrid.java
  android/Drawer/app/src/main/java/com/example/drawer/DrawControl.java
  android/Drawer/app/src/main/java/com/example/drawer/MainActivity.java
  android/Drawer/app/src/main/res/layout/activity_draw_control.xml
Labels: enhancement, Sprint #2

#53 Implement MegaLinter
  .github/workflows/java-lint.yml
  .github/workflows/mega-linter.yml
  .mega-linter.yml
  android/Drawer/app/src/androidTest/java/com/example/drawer/ExampleInstrumentedTest.java
  android/Drawer/app/src/main/java/com/example/drawer/CanvasGrid.java
  android/Drawer/app/src/main/java/com/example/drawer/DrawControl.java
  android/Drawer/app/src/main/java/com/example/drawer/MQTTController.java
  android/Drawer/app/src/main/java/com/example/drawer/MainActivity.java
  android/Drawer/app/src/main/java/com/example/drawer/ManualControl.java
  android/Drawer/app/src/test/java/com/example/drawer/ExampleUnitTest.java
  checkstyle-config.xml
  tools/mqtt-testing/src/main/java/MQTTPublisher.java
Labels: documentation, question, Sprint #3

#54 Mqtt expansion
  android/Drawer/app/build.gradle
  android/Drawer/app/src/main/AndroidManifest.xml
  android/Drawer/app/src/main/java/com/example/drawer/MQTTController.java
  android/Drawer/app/src/main/java/com/example/drawer/MainActivity.java
  android/Drawer/app/src/main/java/com/example/drawer/ManualControl.java
  android/Drawer/build.gradle
  android/Drawer/gradle/wrapper/gradle-wrapper.properties
Labels: enhancement, Sprint #3

#56 Saving Drawn paths
  android/Drawer/app/src/main/java/com/example/drawer/DrawControl.java
  android/Drawer/app/src/main/res/layout/activity_draw_control.xml
Labels: enhancement, Sprint #3

#58 Implements further DrawControl functionality
  android/Drawer/app/src/main/java/com/example/drawer/CanvasGrid.java
  android/Drawer/app/src/main/java/com/example/drawer/DrawControl.java
  android/Drawer/app/src/main/java/com/example/drawer/Vector.java
  android/Drawer/app/src/main/java/com/example/drawer/VectorMap.java
  android/Drawer/app/src/main/res/layout/activity_draw_control.xml
Labels: enhancement, Sprint #3

#62 Read me update
  README.md
Labels: documentation, Sprint #3

#63 Implement obstacle detection
  android/Drawer/app/build.gradle
  android/Drawer/app/src/main/java/com/example/drawer/DrawControl.java
  android/Drawer/app/src/main/java/com/example/drawer/MQTTController.java
  android/Drawer/app/src/main/java/com/example/drawer/MainActivity.java
  android/Drawer/app/src/main/java/com/example/drawer/ManualControl.java
  android/Drawer/app/src/main/res/layout/activity_main.xml
  arduino/smartcar/smartcar.ino
Labels: Sprint #4

#65 Implement joystick path saving
  android/Drawer/app/src/main/java/com/example/drawer/DBManager.java
  android/Drawer/app/src/main/java/com/example/drawer/MainActivity.java
  android/Drawer/app/src/main/java/com/example/drawer/ManualControl.java
  android/Drawer/app/src/main/java/com/example/drawer/ManualRecordingRun.java
  android/Drawer/app/src/main/res/anim/fade_in.xml
  android/Drawer/app/src/main/res/anim/fade_out.xml
  android/Drawer/app/src/main/res/drawable/drawbot.png
  android/Drawer/app/src/main/res/drawable/icon.png
  android/Drawer/app/src/main/res/drawable/logo_animated_vector.xml
  android/Drawer/app/src/main/res/drawable/menu_item_vector.xml
  android/Drawer/app/src/main/res/drawable/smoke_vector.xml
  android/Drawer/app/src/main/res/layout/activity_main.xml
  android/Drawer/app/src/main/res/layout/activity_manual_control.xml
  android/Drawer/app/src/main/res/layout/activity_view_saved_paths.xml
  android/Drawer/app/src/main/res/layout/record_path_save.xml
  android/Drawer/settings.gradle
Labels: documentation, enhancement, Sprint #4

#66 Implements path extraction from canvas and sends movement instructions to the car
  android/Drawer/app/src/main/java/com/example/drawer/CanvasGrid.java
  android/Drawer/app/src/main/java/com/example/drawer/DrawControl.java
  android/Drawer/app/src/main/java/com/example/drawer/Instruction.java
  android/Drawer/app/src/main/java/com/example/drawer/MQTTController.java
  android/Drawer/app/src/main/java/com/example/drawer/MainActivity.java
  android/Drawer/app/src/main/java/com/example/drawer/ManualControl.java
  android/Drawer/app/src/main/java/com/example/drawer/PathInstructionSet.java
  android/Drawer/app/src/main/java/com/example/drawer/Vector.java
  android/Drawer/app/src/main/java/com/example/drawer/VectorMap.java
  android/Drawer/app/src/main/res/layout/activity_draw_control.xml
  android/Drawer/app/src/main/res/layout/activity_draw_saves.xml
  android/Drawer/app/src/main/res/layout/activity_main.xml
  android/Drawer/app/src/main/res/layout/activity_manual_control.xml
  arduino/smartcar/smartcar.ino
Labels: enhancement, Sprint #4

#69 Fix crash with DrawControl
  android/Drawer/app/src/main/java/com/example/drawer/CanvasGrid.java
  android/Drawer/app/src/main/java/com/example/drawer/DrawControl.java
Labels: Sprint #4

#71 Adds build badges and minor edits to installation section of README
  README.md
Labels: documentation, Sprint #4

#72 Adds a component diagram and a link to demo video
  README.md
Labels: documentation, Sprint #4
