Repository DIT113-V22/group-04, pull requests merged in 2022-04, with the labels that each got.

#16 Add templates
  .github/ISSUE_TEMPLATE/user_story_template.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: documentation, Sprint #1

#18 Implement Android build action
  .github/workflows/android-build.yml
  .github/workflows/arduino-build.yml
Labels: Sprint #1, tests

#20 Android App Set Up
  .github/workflows/android-build.yml
  android/Drawer/.gitignore
  android/Drawer/app/.gitignore
  android/Drawer/app/build.gradle
  android/Drawer/app/proguard-rules.pro
  android/Drawer/app/src/androidTest/java/com/example/drawer/ExampleInstrumentedTest.java
  android/Drawer/app/src/main/AndroidManifest.xml
  android/Drawer/app/src/main/java/com/example/drawer/MainActivity.java
  android/Drawer/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  android/Drawer/app/src/main/res/drawable/ic_launcher_background.xml
  android/Drawer/app/src/main/res/layout/activity_main.xml
  android/Drawer/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/Drawer/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/Drawer/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  android/Drawer/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  android/Drawer/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  android/Drawer/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  android/Drawer/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  android/Drawer/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  android/Drawer/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  android/Drawer/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  android/Drawer/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  android/Drawer/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  android/Drawer/app/src/main/res/values-night/themes.xml
  android/Drawer/app/src/main/res/values/colors.xml
  android/Drawer/app/src/main/res/values/strings.xml
  android/Drawer/app/src/main/res/values/themes.xml
  android/Drawer/app/src/test/java/com/example/drawer/ExampleUnitTest.java
  android/Drawer/build.gradle
  android/Drawer/gradle.properties
  android/Drawer/gradle/wrapper/gradle-wrapper.jar
  android/Drawer/gradle/wrapper/gradle-wrapper.properties
  android/Drawer/gradlew
  android/Drawer/gradlew.bat
  android/Drawer/settings.gradle
Labels: enhancement, Sprint #1

#35 Manual Control Integration
  android/Drawer/app/build.gradle
  android/Drawer/app/src/main/AndroidManifest.xml
  android/Drawer/app/src/main/ic_launcher-playstore.png
  android/Drawer/app/src/main/java/com/example/drawer/DrawControl.java
  android/Drawer/app/src/main/java/com/example/drawer/MQTTController.java
  android/Drawer/app/src/main/java/com/example/drawer/MainActivity.java
  android/Drawer/app/src/main/java/com/example/drawer/ManualControl.java
  android/Drawer/app/src/main/res/drawable/ic_launcher_background.xml
  android/Drawer/app/src/main/res/drawable/inner_circle.xml
  android/Drawer/app/src/main/res/drawable/outer_circle.xml
  android/Drawer/app/src/main/res/layout/activity_draw_control.xml
  android/Drawer/app/src/main/res/layout/activity_main.xml
  android/Drawer/app/src/main/res/layout/activity_manual_control.xml
  android/Drawer/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/Drawer/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/Drawer/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/Drawer/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  android/Drawer/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/Drawer/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/Drawer/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  android/Drawer/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/Drawer/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  android/Drawer/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/Drawer/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/Drawer/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  android/Drawer/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/Drawer/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  android/Drawer/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/Drawer/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/Drawer/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  android/Drawer/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/Drawer/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  android/Drawer/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/Drawer/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/Drawer/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  android/Drawer/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/Drawer/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  android/Drawer/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/Drawer/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/Drawer/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  android/Drawer/app/src/main/res/values-night/themes.xml
  android/Drawer/app/src/main/res/values/ic_launcher_background.xml
  android/Drawer/app/src/main/res/values/themes.xml
  android/Drawer/build.gradle
  android/Drawer/settings.gradle
  arduino/smartcar/smartcar.ino
Labels: Sprint #1
